# docker/docker-compose.yml
# Defines the multi-container application services.

version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: trading_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt # For SSL certificates
    depends_on:
      - app
    networks:
      - trading_network

  # Main Python Application
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: trading_app
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ..:/app
    depends_on:
      - db
      - redis
    networks:
      - trading_network

  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: trading_db
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - trading_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: trading_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - trading_network

volumes:
  postgres_data:

networks:
  trading_network:
    driver: bridge
